"""Markdown report generator for backtest results."""

from __future__ import annotations

import textwrap
from typing import Any

from trading_lab.backtest.engine import BacktestResult


def render_report(result: BacktestResult) -> str:
    m = result.metrics
    lines: list[str] = []

    lines.append(f"# Backtest: {result.strategy_name} — {result.ticker}")
    lines.append("")

    # -- Metrics table -------------------------------------------------
    lines.append("## Metrics")
    lines.append("")
    lines.append("| Metric | Value |")
    lines.append("|---|---|")
    lines.append(f"| Initial capital | ${result.initial_capital:,.2f} |")
    lines.append(f"| Final equity | ${result.final_equity:,.2f} |")
    _add(lines, m, "total_return_pct", "Total return", "%")
    _add(lines, m, "cagr_pct", "CAGR", "%")
    _add(lines, m, "sharpe_ratio", "Sharpe ratio", "")
    _add(lines, m, "max_drawdown_pct", "Max drawdown", "%")
    _add(lines, m, "win_rate", "Win rate", "%")
    _add(lines, m, "profit_factor", "Profit factor", "")
    _add(lines, m, "total_trades", "Total trades", "")
    _add(lines, m, "winning_trades", "Winning trades", "")
    _add(lines, m, "losing_trades", "Losing trades", "")
    _add(lines, m, "avg_win_pct", "Avg win", "%")
    _add(lines, m, "avg_loss_pct", "Avg loss", "%")
    lines.append("")

    # -- Trades --------------------------------------------------------
    lines.append("## Trades")
    lines.append("")
    if result.trades:
        lines.append("| # | Entry | Exit | Entry $ | Exit $ | P&L | Return % |")
        lines.append("|---|---|---|---|---|---|---|")
        for i, t in enumerate(result.trades, 1):
            pnl_str = f"${t.pnl:+.2f}" if t.pnl is not None else "—"
            ret_str = f"{t.return_pct:+.2f}%" if t.return_pct is not None else "—"
            lines.append(
                f"| {i} | {t.entry_date} | {t.exit_date or '—'} | "
                f"${t.entry_price:.2f} | ${t.exit_price or 0:.2f} | "
                f"{pnl_str} | {ret_str} |"
            )
    else:
        lines.append("No trades executed.")
    lines.append("")

    # -- Signals summary -----------------------------------------------
    lines.append("## Signals")
    lines.append("")
    buy_count = sum(1 for s in result.signals if s.action.value == "BUY")
    sell_count = sum(1 for s in result.signals if s.action.value == "SELL")
    hold_count = sum(1 for s in result.signals if s.action.value == "HOLD")
    lines.append(f"- BUY: {buy_count}")
    lines.append(f"- SELL: {sell_count}")
    lines.append(f"- HOLD: {hold_count}")
    lines.append(f"- Total: {len(result.signals)}")
    lines.append("")

    # -- Equity curve (ASCII sparkline) --------------------------------
    lines.append("## Equity curve")
    lines.append("")
    if len(result.equity_curve) > 1:
        lines.append(_sparkline(result.equity_curve))
    lines.append("")

    lines.append("---")
    lines.append("*Generated by Sid Trading Lab backtest engine v1.*")
    lines.append("")

    return "\n".join(lines)


def _add(lines: list[str], m: dict, key: str, label: str, suffix: str) -> None:
    val = m.get(key)
    if val is not None:
        lines.append(f"| {label} | {val}{suffix} |")


def _sparkline(equity_curve: list[dict[str, Any]], width: int = 40) -> str:
    values = [pt["equity"] for pt in equity_curve]
    lo = min(values)
    hi = max(values)
    rng = hi - lo if hi > lo else 1

    chars = "▁▂▃▄▅▆▇█"
    result: list[str] = []
    for v in values:
        idx = int((v - lo) / rng * (len(chars) - 1))
        result.append(chars[min(idx, len(chars) - 1)])

    # Downsample to ~width chars.
    if len(result) > width:
        step = len(result) / width
        result = [result[int(i * step)] for i in range(width)]

    start = f"${lo:,.0f} "
    end = f" ${hi:,.0f}"
    return f"```\n{start}{''.join(result)}{end}\n```"
