"""Markdown report generator for parameter sweep results."""

from __future__ import annotations

from typing import Any

from trading_lab.backtest.sweep import SweepResult


def render_sweep_report(result: SweepResult) -> str:
    lines: list[str] = []

    lines.append(f"# Parameter Sweep: {result.strategy_name} — {result.ticker}")
    lines.append("")

    # Grid description
    lines.append("## Parameters Tested")
    lines.append("")
    for param, values in result.params_grid.items():
        lines.append(f"- **{param}**: {values}")
    lines.append(f"- **Total combinations**: {len(result.results)}")
    lines.append(f"- **Ranked by**: {result.best_metric}")
    lines.append("")

    # Best result
    if result.best:
        lines.append("## Best Combination")
        lines.append("")
        lines.append(f"| Parameter | Value |")
        lines.append("|---|---|")
        for k, v in result.best_params.items():
            lines.append(f"| {k} | {v} |")
        lines.append("")
        lines.append("### Best Performance")
        lines.append("")
        m = result.best.metrics
        lines.append("| Metric | Value |")
        lines.append("|---|---|")
        lines.append(f"| Total return | {m.get('total_return_pct', '—')}% |")
        lines.append(f"| CAGR | {m.get('cagr_pct', '—')}% |")
        lines.append(f"| Sharpe ratio | {m.get('sharpe_ratio', '—')} |")
        lines.append(f"| Max drawdown | {m.get('max_drawdown_pct', '—')}% |")
        lines.append(f"| Win rate | {m.get('win_rate', '—')}% |")
        lines.append(f"| Profit factor | {m.get('profit_factor', '—')} |")
        lines.append(f"| Total trades | {m.get('total_trades', '—')} |")
        lines.append(f"| Strategy | {result.best.strategy_name} |")
        lines.append("")

    # Full ranking table
    lines.append("## All Combinations (Ranked)")
    lines.append("")
    if result.results:
        headers = ["Params", "Return %", "Sharpe", "Max DD %", "Win Rate %", "Profit Factor", "Trades"]
        lines.append("| " + " | ".join(headers) + " |")
        lines.append("|" + "---|" * len(headers))

        for r in result.results:
            name = r.strategy_name
            params = name.split("(", 1)[1].rstrip(")") if "(" in name else name
            m = r.metrics
            lines.append(
                f"| {params} | "
                f"{m.get('total_return_pct', '-')} | "
                f"{m.get('sharpe_ratio', '-')} | "
                f"{m.get('max_drawdown_pct', '-')} | "
                f"{m.get('win_rate', '-')} | "
                f"{m.get('profit_factor', '-')} | "
                f"{m.get('total_trades', '-')} |"
            )
    lines.append("")

    lines.append("---")
    lines.append("*Generated by Sid Trading Lab parameter sweep engine v1.*")
    lines.append("")

    return "\n".join(lines)
