"""Markdown renderer for strategy factsheet."""
from __future__ import annotations


def render_factsheet(data: dict) -> str:
    lines = []
    lines.append(f"# Strategy Factsheet: {data['strategy']} — {data['ticker']}")
    lines.append("")

    meta = data["metadata"]
    lines.append("## Strategy Hypothesis")
    lines.append("")
    lines.append(f"**Category:** {meta.get('category', 'N/A')}")
    lines.append(f"**Hypothesis:** {meta.get('hypothesis', 'N/A')}")
    lines.append(f"**Expected Regime:** {meta.get('expected_market_regime', 'N/A')}")
    lines.append(f"**Required Data:** {meta.get('required_data', 'close')}")
    lines.append("")
    lines.append("**Parameters:**")
    for k, (default, desc) in meta.get("parameters", {}).items():
        lines.append(f"- `{k}`: {desc} (default: {default})")
    lines.append("")
    lines.append("**Failure Modes:**")
    for fm in meta.get("failure_modes", []):
        lines.append(f"- {fm}")
    lines.append("")

    bt = data["backtest"]
    m = bt["metrics"]
    lines.append("## Backtest Performance")
    lines.append("")
    lines.append("| Metric | Value |")
    lines.append("|---|---|")
    lines.append(f"| Initial capital | ${bt['initial_capital']:,.2f} |")
    lines.append(f"| Final equity | ${bt['final_equity']:,.2f} |")
    lines.append(f"| Total return | {m.get('total_return_pct', '-')}% |")
    lines.append(f"| CAGR | {m.get('cagr_pct', '-')}% |")
    lines.append(f"| Sharpe ratio | {m.get('sharpe_ratio', '-')} |")
    lines.append(f"| Max drawdown | {m.get('max_drawdown_pct', '-')}% |")
    lines.append(f"| Win rate | {m.get('win_rate', '-')}% |")
    lines.append(f"| Profit factor | {m.get('profit_factor', '-')} |")
    lines.append(f"| Total trades | {m.get('total_trades', '-')} |")
    lines.append("")

    bench = data["benchmark"]
    lines.append("## Benchmark Comparison (Buy & Hold)")
    lines.append("")
    lines.append("| Metric | Value |")
    lines.append("|---|---|")
    lines.append(f"| Buy & Hold return | {bench.get('buy_and_hold_return_pct', '-')}% |")
    lines.append(f"| Strategy return | {bench.get('strategy_return_pct', '-')}% |")
    outperf = bench.get("outperformance_pct")
    if outperf is not None:
        lines.append(f"| Outperformance | {outperf:+.2f}% |")
    lines.append("")

    costs = data["cost_sensitivity"]
    lines.append("## Cost Sensitivity")
    lines.append("")
    lines.append("| Scenario | Commission | Slippage | Return % | Sharpe | Max DD % | Trades |")
    lines.append("|---|---|---|---|---|---|---|")
    for c in costs:
        lines.append(f"| {c['scenario']} | {c['commission_pct']} | {c['slippage_pct']} | {c['total_return_pct'] or '-'} | {c['sharpe_ratio'] or '-'} | {c['max_drawdown_pct'] or '-'} | {c['total_trades'] or '-'} |")
    lines.append("")

    stab = data["parameter_stability"]
    if stab and "best_params" in stab:
        lines.append("## Parameter Stability")
        lines.append("")
        lines.append("| Metric | Value |")
        lines.append("|---|---|")
        lines.append(f"| Combinations tested | {stab.get('combinations', '-')} |")
        lines.append(f"| Mean return | {stab.get('mean_return', '-')}% |")
        lines.append(f"| Std return | {stab.get('std_return', '-')}% |")
        cv = stab.get("cv")
        if cv is not None:
            lines.append(f"| CV | {cv} |")
        lines.append(f"| Stable range | {'Yes' if stab.get('stable_range') else 'No'} |")
        if stab.get("best_params"):
            lines.append(f"| Best params | {stab['best_params']} |")
        bm = stab.get("best_metrics")
        if bm:
            lines.append("")
            lines.append("**Best combo metrics:**")
            lines.append(f"- Return: {bm.get('total_return_pct', '-')}%")
            lines.append(f"- Sharpe: {bm.get('sharpe_ratio', '-')}")
            lines.append(f"- Max DD: {bm.get('max_drawdown_pct', '-')}%")
            lines.append(f"- Win rate: {bm.get('win_rate', '-')}%")
        lines.append("")

    lines.append("## Market Regime Notes")
    lines.append("")
    lines.append(f"Expected regime: **{meta.get('expected_market_regime', 'any')}**")
    lines.append("")
    lines.append("**What can go wrong:**")
    for fm in meta.get("failure_modes", []):
        lines.append(f"- {fm}")
    lines.append("")

    verdict = data.get("verdict", "watch")
    emoji_map = {"research": "[green]", "watch": "[yellow]", "reject": "[red]"}
    lines.append("## Verdict")
    lines.append("")
    lines.append(f"**{verdict.upper()}**")
    lines.append("")
    lines.append("---")
    lines.append("*Generated by Sid Trading Lab Factsheet Engine v1.*")
    lines.append("")
    return "\n".join(lines)
