"""Markdown report generator for shadow account results."""

from __future__ import annotations

from trading_lab.shadow.account import ShadowResult


def render_shadow_report(result: ShadowResult) -> str:
    lines: list[str] = []

    lines.append(f"# Shadow Account: {result.strategy_name} — {result.ticker}")
    lines.append("")
    if result.from_date:
        lines.append(f"**Period:** {result.from_date} → {result.to_date}")
    lines.append(f"**Generated:** {result.generated_at}")
    lines.append("")

    # -- Summary --------------------------------------------------------
    lines.append("## Summary")
    lines.append("")
    lines.append(
        "The **shadow** column shows what a mechanical, zero-discretion "
        "execution of the strategy would have produced.  The **actual** "
        "column reflects your journaled signals.  Gaps between them "
        "are behavioral drift."
    )
    lines.append("")

    lines.append("| Metric | Shadow (mechanical) | Actual (journaled) |")
    lines.append("|---|---|---|")
    lines.append(f"| Trades | {result.shadow_trades} | {result.buy_signals + result.sell_signals} |")
    lines.append(f"| Return | {result.shadow_return_pct:+.2f}% | — |")
    if result.shadow_sharpe is not None:
        lines.append(f"| Sharpe | {result.shadow_sharpe:.2f} | — |")
    lines.append(f"| Signals total | — | {result.total_signals_journaled} |")
    lines.append(f"| BUY | — | {result.buy_signals} |")
    lines.append(f"| SELL | — | {result.sell_signals} |")
    lines.append(f"| HOLD | — | {result.hold_signals} |")
    lines.append("")

    # -- Drift metrics --------------------------------------------------
    lines.append("## Drift metrics")
    lines.append("")
    lines.append("| Metric | Value | Interpretation |")
    lines.append("|---|---|---|")
    _drift_row(lines, "Signal adherence", result.adherence_pct, "%",
               ">80% = disciplined, <50% = significant deviation",
               lambda v: "green" if v >= 80 else "yellow" if v >= 50 else "red")
    _drift_row(lines, "Missed entries", result.missed_entries, "",
               "Buy signals the strategy generated that weren't in your journal",
               lambda v: "green" if v == 0 else "yellow" if v <= 2 else "red")
    _drift_row(lines, "Extra signals", result.extra_signals, "",
               "Journal entries beyond what strict strategy-following produces",
               lambda v: "green" if v == 0 else "yellow" if v <= 3 else "red")
    _drift_row(lines, "HOLD overrides", result.signals_overridden, "",
               "Times you chose HOLD when the strategy had conviction",
               lambda v: "green" if v == 0 else "yellow" if v <= 2 else "red")
    _drift_row(lines, "Overtrading score", result.overtrading_score, "/100",
               "0 = perfect discipline, 100 = total deviation from plan",
               lambda v: "green" if v < 20 else "yellow" if v < 50 else "red")
    lines.append("")

    # -- Gap analysis ---------------------------------------------------
    lines.append("## Behavioral gap analysis")
    lines.append("")
    for note in result.gap_notes:
        lines.append(f"- {note}")
    lines.append("")

    # -- Interpretation guide -------------------------------------------
    lines.append("## How to read this")
    lines.append("")
    lines.append(
        "- **Shadow return positive, you didn't act** — the strategy saw "
        "something you missed.  Review the signal and ask why you passed."
    )
    lines.append(
        "- **Many HOLD overrides** — you're overriding the strategy.  Either "
        "your intuition is better (track it to prove it) or you're "
        "second-guessing a system you built."
    )
    lines.append(
        "- **High overtrading score** — you're generating noise, not signals.  "
        "Consider tightening your entry criteria or journaling fewer tickers."
    )
    lines.append(
        "- **Zero drift** — unlikely in practice.  Some divergence is normal.  "
        "The goal is awareness, not robotic adherence."
    )
    lines.append("")

    lines.append("---")
    lines.append("*Generated by Sid Trading Lab shadow account v1.*")
    lines.append("*The shadow doesn't judge. It just shows what the strategy would have done.*")
    lines.append("")

    return "\n".join(lines)


def _drift_row(
    lines: list[str],
    label: str,
    value: float | int | None,
    suffix: str,
    interpretation: str,
    _color: callable,
) -> None:
    if value is None:
        lines.append(f"| {label} | — | {interpretation} |")
    else:
        lines.append(f"| {label} | {value}{suffix} | {interpretation} |")
