"""Alpha Integration — wire simulation results into Phase 2 meta-learning.

Phase 3 Milestone 6: If simulation winner beats baseline, export as strategy
and run through Phase 2 sandbox + validator + adoption pipeline.
"""
from __future__ import annotations

import logging
import os
from pathlib import Path

from trading_lab.alpha.analytics import SimulationAnalytics, SimulationReport
from trading_lab.alpha.features import FeatureEngine
from trading_lab.alpha.neural_signal import NeuralSignalModel
from trading_lab.meta.adoption_manager import AdoptionManager
from trading_lab.meta.sandbox import SyntaxSandbox
from trading_lab.meta.variant_validator import VariantValidator
from trading_lab.meta.change_log import ChangeLog

logger = logging.getLogger(__name__)


NEURAL_STRATEGY_TEMPLATE = '''"""Auto-generated neural-augmented strategy.

Generated by Phase 3 Alpha Discovery pipeline.
Trained on features: {feature_names}
"""
from __future__ import annotations

import numpy as np
from trading_lab.models import Signal, SignalAction
from trading_lab.strategies.base import Strategy
from trading_lab.alpha.neural_signal import NeuralSignalModel
from trading_lab.alpha.features import FeatureEngine, compute_features_for_tickers

class NeuralAugmentedStrategy(Strategy):
    """Neural signal strategy auto-generated from simulation."""

    def __init__(self):
        super().__init__()
        self.model = NeuralSignalModel()
        self.engine = FeatureEngine()
        # Weights are serialized here (simplified — in production load from file)
{weight_code}

    def generate_signal(self, ticker: str, prices: list[float]) -> Signal:
        if len(prices) < 20:
            return Signal(strategy=self.__class__.__name__, ticker=ticker,
                          action=SignalAction.HOLD, confidence=0.0, reason="insufficient data")
        # Build minimal OHLCV arrays (close only for simplicity)
        close = np.array(prices)
        # Approximate other fields from close
        open_ = close  # approximation
        high = close * 1.01  # approximation
        low = close * 0.99  # approximation
        volume = np.ones_like(close) * 1e6  # approximation

        fs = self.engine.compute(ticker, open_, high, low, close, volume)
        result = self.model.predict(fs)
        action = getattr(SignalAction, result.action, SignalAction.HOLD)
        return Signal(
            strategy=self.__class__.__name__,
            ticker=ticker,
            action=action,
            confidence=result.confidence,
            reason=f"neural_{result.action}",
        )
'''


class AlphaIntegration:
    """Integrate Phase 3 alpha discovery with Phase 2 adoption pipeline."""

    ALPHA_THRESHOLD = 0.05
    SHARPE_THRESHOLD = 0.50

    def __init__(self):
        self.analytics = SimulationAnalytics()
        self.adoption = AdoptionManager()
        self.validator = VariantValidator()
        self.sandbox = SyntaxSandbox()

    def process_simulation(
        self,
        report: SimulationReport,
        auto_adopt: bool = False,
    ) -> dict[str, str]:
        """Process simulation report. If winner is good, export and validate.

        Returns dict with keys: action, strategy_id, reason, validation_passed.
        """
        if report.alpha_pct < self.ALPHA_THRESHOLD or report.best_sharpe < self.SHARPE_THRESHOLD:
            return {
                "action": "skip",
                "strategy_id": report.best_agent,
                "reason": (
                    f"Alpha {report.alpha_pct:.1%} < {self.ALPHA_THRESHOLD:.0%} "
                    f"or Sharpe {report.best_sharpe:.2f} < {self.SHARPE_THRESHOLD:.2f}"
                ),
                "validation_passed": "n/a",
            }

        best = report.leaderboard[0] if report.leaderboard else None
        if not best:
            return {"action": "skip", "reason": "No leaderboard entries", "validation_passed": "n/a"}

        # If winner is neural, export as Python strategy
        if best.is_neural:
            strategy_id = f"neural_{report.sim_id[:8]}"
            source = self._export_neural_strategy(strategy_id, report)
            # Validate
            sandbox_result = SyntaxSandbox.validate(source)
            if not sandbox_result.valid:
                return {
                    "action": "skip",
                    "strategy_id": strategy_id,
                    "reason": f"Sandbox failed: {sandbox_result.error}",
                    "validation_passed": "false",
                }

            # Run backtest validation
            val_result = self.validator.validate(source, baseline="simple_momentum")
            if not val_result or not val_result.passes:
                reason = val_result.reason if val_result else "Validation returned None"
                return {
                    "action": "skip",
                    "strategy_id": strategy_id,
                    "reason": f"Validation failed: {reason}",
                    "validation_passed": "false",
                }

            if auto_adopt:
                adopt_result = self.adoption.adopt(
                    variant_source=source,
                    variant_name=strategy_id,
                    baseline_id="simple_momentum",
                    validation=val_result,
                )
                return {
                    "action": "adopted",
                    "strategy_id": strategy_id,
                    "reason": f"Auto-adopted: {adopt_result.action}",
                    "validation_passed": "true",
                    "git_commit": adopt_result.git_commit or "",
                }
            else:
                # Save to file for manual review
                variant_path = Path(f"variants/{strategy_id}.py")
                variant_path.parent.mkdir(exist_ok=True)
                variant_path.write_text(source)
                return {
                    "action": "exported",
                    "strategy_id": strategy_id,
                    "reason": f"Exported to {variant_path}. Run adopt-variant to adopt.",
                    "validation_passed": "true",
                }

        # If winner is existing strategy variant, just report
        return {
            "action": "report",
            "strategy_id": best.agent_id,
            "reason": f"Existing strategy '{best.agent_id}' won simulation. No export needed.",
            "validation_passed": "n/a",
        }

    def _export_neural_strategy(self, strategy_id: str, report: SimulationReport) -> str:
        """Generate Python source for a neural-augmented strategy."""
        # Simplified: create template with placeholder weights
        # In production, serialize actual model weights as base64 or numpy save
        feature_names = [
            "rsi_14", "atr_14_pct", "price_vs_sma_20", "price_vs_sma_50",
            "volume_zscore_20", "momentum_5d", "momentum_20d",
            "bb_width", "atr_rank_20", "volume_ma_20",
        ]
        weight_code = "        # Model weights loaded from serialized state\n        pass"
        return NEURAL_STRATEGY_TEMPLATE.format(
            strategy_id=strategy_id,
            feature_names=", ".join(feature_names),
            weight_code=weight_code,
        )

    def run_full_pipeline(
        self,
        tickers: list[str] | None = None,
        lookback_days: int = 30,
        auto_adopt: bool = False,
    ) -> dict[str, str]:
        """Run full Phase 3 pipeline: simulate → analyze → integrate.

        Returns result dict.
        """
        from trading_lab.alpha.simulation import MultiAgentSimulation

        tickers = tickers or ["SPY", "AAPL", "MSFT"]
        sim = MultiAgentSimulation(
            lookback_days=lookback_days,
            tickers=tickers,
        )
        results = sim.run()

        from datetime import datetime, timezone
        sim_id = f"sim_{datetime.now(timezone.utc).strftime('%Y%m%d_%H%M%S')}"
        report = self.analytics.analyze(
            results=results,
            sim_id=sim_id,
            timestamp=datetime.now(timezone.utc).isoformat(),
            tickers=tickers,
            lookback_days=lookback_days,
        )

        # Log to change_log
        cl = ChangeLog()
        cl.record(
            strategy_id=report.best_agent,
            action="alpha_discovered",
            reason=report.recommendation,
            composite_score=report.best_sharpe,
        )

        return self.process_simulation(report, auto_adopt=auto_adopt)
